################################# Default configuration ###################
# provide your domain here
baseURL = "https://www.koompi.org/"

# theme
theme = "dot"
# site title
title = "KOOMPI OS"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]
name = "Faqs"
url = "faqs"
weight = 1

#[[menu.main]]
#name = "contact"
#url = "contact"
#weight = 2

[[menu.main]]
name = "Download"
url = "https://repo.koompi.org/iso/KOOMPI-OS-2020.04.26-x86_64.iso"
weight = 3

[[menu.main]]
weight = 4
name = "videos"
hasChildren = true
    
  [[menu.main]]
  parent = "videos"
  name = "Interviews"
  url = "interview"
  weight = 1

  [[menu.main]]
  parent = "videos"
  name = "Tutorials"
  url = "tutorial"
  weight = 2


############################# Default Parameters ##########################
[params]
# logo is for all page
logo =""
# logo white is for homepage logo, you can use colorful logo too...
logo_white =""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/koompi/"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/koompi_official"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/koompi"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://linkedin.com/company/koompi"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "Copyright by  © KOOMPI 2020 "


# banner
[Languages.en.params.banner]
title = "Support Center & Knowledgebase"
subtitle = "Find advice and answers from our support team fast or get in touch"
bg_image = "images/lightblack.png"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "If you could not find any answers related to the problems, let us know by submitting the problems."

# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################################### Khmer Language ######################
[Languages.kh]
languageName = "Kh"
languageCode = "kh-kh"
weight = 2
home = "ទំព័រដើម"
Faqs= "សំនួរ&​ចំលើយ" 
copyright = "រក្សាសិទ្ធិដោយ © គម្ពីរ ២០២០"

# banner
[Languages.kh.params.banner]
title = "មជ្ឈមណ្ឌលសម្របសម្រួលនិង មូលដ្ឋាននៃចំណេះដឹង"
subtitle = "ស្វែងរកដំបូន្មាន និងចម្លើយពីអ្នកសម្របសម្រួលរបស់យើងបានយ៉ាងឆាប់រហ័ស"
bg_image = "images/lightblack.png"
placeholder = "មានសំណួរមែនទេ?  អាចធ្វើការស្វែងរកនៅទីនេះ..."

# call to action
[Languages.kh.params.cta]
enable = true
title = "រកមិនឃើញចម្លើយសម្រាប់សំណួររបស់អ្នកមែនទេ??"
content = "ប្រសិនបើអ្នកមិនអាចរកឃើញដំណោះស្រាយទាក់ទងនឹងបញ្ហារបស់អ្នក អ្នកអាចធ្វើការទំនាក់ទំនងមក​យើងខ្ញុំ ឬដោយដាក់ស្នើពីបញ្ហានោះបាន។"
# call to action button
[Languages.kh.params.cta.button]
enable = true
label = "ធ្វើទាក់ទង​មក​យើងខ្ញុំ"
link = "contact"
